[package]
name = "minimesh-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
nalgebra = "0.31.1"
float-ord = "0.3.2"
nom_stl = "0.2.2"